name: allure-report
on:
    push:
        branches:
            - run_action
jobs:
    generate-report:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3

            - name: Download Cypress
              run: | 
                npm install

            - name: Run Cypress
              continue-on-error: true
              run: npx cypress run --env allure=true
            
            - name: Generate Allure Report
              uses: simple-elf/allure-report-action@master
              if: always()
              with:
                  allure_results: allure-results
            
            - name: Generate html report
              run: npm run reportNow