name: allure-report
on:
    push:
        branches:
            - master
jobs:
    generate-report:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3

            - name: Download Cypress
              run: | 
                npm install
                cat package.json
                ls
                npx cypress --version

            - name: Run Cypress
              continue-on-error: true
              run: npx cypress run --env allure=true
            
            - name: check test result
              run: ls